version: "3.9"
services:
  mysql:
      environment:
          - MYSQL_DATABASE=root
          - MYSQL_ROOT_PASSWORD=root
      command:
         - --table_definition_cache=100
         - --performance_schema=0
         - --default-authentication-plugin=mysql_native_password
         - --innodb_use_native_aio=0
      volumes:
          - /root/swarmon/mysql/init:/docker-entrypoint-initdb.d
          - /root/swarmon/mysql/databases:/var/lib/mysql
      container_name: mysql1
      ports:
          - 3306:3306
      image: mysql
      restart: always
  grafana:
      container_name: grafana_swarm
      image: ytx1991/grafana_swarm:latest
      volumes:
           - /root/swarmon/grafana:/var/lib/grafana
      ports:
          - 3000:3000
      restart: always
  swarmmon:
      container_name: swarmmon1
      image: ytx1991/swarmmon
      ports:
          - 8080:8080
      restart: always
volumes:
      databases: {}
