version: "3.9"
services:
  grafana:
      container_name: grafana_swarm
      image: grafana/grafana
      network_mdoe: "host"
      volumes:
          - /root/swarmon/grafana:/var/lib/grafana
      restart: always
  prometheus:
      container_name: prometheus
      image: prom/prometheus
      volumes:
          - /root/swarmon/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      network_mdoe: "host"
      restart: always
