{
 "title": "我的节点",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "各节点出票数",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timeof AS \"time\",\n  name AS metric,\n  cheque\nFROM nodes\nWHERE\n  $__timeFilter(timeof) AND name!=\"\"\nORDER BY name"
    }
   ]
  },
  {
   "title": "各节点尚未提现BZZ",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timeof AS \"time\",\n  name AS metric,\n  totaluncashed\nFROM nodes\nWHERE\n  $__timeFilter(timeof) AND name!=\"\"\nORDER BY timeof"
    }
   ]
  },
  {
   "title": "各节点持有BZZ",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timeof AS \"time\",\n  name AS metric,\n  availableBZZ\nFROM nodes\nWHERE\n  $__timeFilter(timeof) AND name!=\"\"\nORDER BY name"
    }
   ]
  },
  {
   "title": "Active Peers",
   "type": "graph",
   "description": "Peers, updating every 10 mins",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  timeof AS \"time\",\n  name AS metric,\n  peers\nFROM nodes\nWHERE\n  $__timeFilter(timeof) AND name != \"\"\nORDER BY timeof"
    }
   ]
  },
  {
   "title": "各节点剩余磁盘空间",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timeof AS \"time\",\n  name AS metric,\n  diskfree\nFROM nodes\nWHERE\n  $__timeFilter(timeof) AND name != \"\"\nORDER BY name"
    }
   ]
  },
  {
   "title": "各节点活跃连接",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timeof AS \"time\",\n  name AS metric,\n  peers\nFROM nodes\nWHERE\n  $__timeFilter(timeof) AND name != \"\"\n  ORDER BY name"
    }
   ]
  }
 ]
}